"""
Loads the charger registry and overlays the daily health-check results onto
it, so the router can see which stations are currently reported working.

Registry file (every_charger_india.json) format:
    {
        "last_updated": "2026-09-15T04:00:00+00:00",
        "chargers": [ {...OCM-shaped charger record...}, ... ]
    }
The old flat-list format (just [ {...}, ... ]) is still accepted for
backwards compatibility with databases generated by the previous version
of this app.

Health file (charger_health.json) format:
    {
        "<charger id>": {
            "is_working": true,
            "confidence": 82,
            "last_checked": "2026-09-15T04:00:00+00:00",
            "reason": "Operational, 3 positive check-ins in last 7 days.",
            "consecutive_failures": 0
        },
        ...
    }
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Tuple

REGISTRY_PATH = "every_charger_india.json"
HEALTH_PATH = "charger_health.json"


def load_registry(path: str = REGISTRY_PATH) -> Tuple[List[Dict[str, Any]], str | None]:
    """Returns (chargers, last_updated_iso_or_none)."""
    if not os.path.exists(path):
        return [], None
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return [], None

    if isinstance(data, list):
        return data, None
    if isinstance(data, dict):
        return data.get("chargers", []), data.get("last_updated")
    return [], None


def load_health(path: str = HEALTH_PATH) -> Dict[str, Dict[str, Any]]:
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}


def merge_health(chargers: List[Dict[str, Any]], health: Dict[str, Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Attaches is_working / health_confidence / health_reason onto each charger, in place."""
    for charger in chargers:
        record = health.get(str(charger.get("ID")))
        if record:
            charger["is_working"] = record.get("is_working", True)
            charger["health_confidence"] = record.get("confidence", 50)
            charger["health_reason"] = record.get("reason", "")
            charger["health_last_checked"] = record.get("last_checked")
            charger["consecutive_failures"] = record.get("consecutive_failures", 0)
        else:
            charger["is_working"] = True  # unchecked stations default to "assume working"
            charger["health_confidence"] = 50
            charger["health_reason"] = "Not yet health-checked."
            charger["health_last_checked"] = None
            charger["consecutive_failures"] = 0
    return chargers


def get_registry_with_health(registry_path: str = REGISTRY_PATH,
                              health_path: str = HEALTH_PATH) -> Dict[str, Any]:
    chargers, last_updated = load_registry(registry_path)
    health = load_health(health_path)
    chargers = merge_health(chargers, health)
    return {
        "chargers": chargers,
        "registry_last_updated": last_updated,
        "health_checked_count": len(health),
    }
